# Project information
site_name: Sistema Multiempresa
site_dir: ../public/docs/user
use_directory_urls: true

# Page tree
nav:
  - Introducción: index.md
  - Requerimientos del sistema: requirements.md
  - Diagramas:
      - Aplicación Base: modules/baseApplicationDiagram.md
  - Casos de uso:
      - Aplicación Base: baseapplicationusecases.md
  - Propuesta técnica: technical_proposal.md
  - Limitaciones de multitenancy en Laravel: limitations.md
  - Intercambio de datos entre clientes (Tenants): data.md
  - Paquete Laravel multitenancy: laravel.md
  - Implementación de un sistema multitenancy simple: example.md
  - Aplicación multitenancy: demo.md

# Repository
repo_name: Repositorio-Kavac
repo_url: https://gestion.cenditel.gob.ve/trac/browser/kavac/

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: es
  features:
    - navigation.tabs
    #- navigation.instant
  palette:
    scheme: default
    primary: light-blue
    accent: light-blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  logo: images/logo.png

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details

# css additional
extra_css:
  - stylesheets/extra.css
